### ISSUE TITLE
Manual annotation in EuropePMC format

### ISSUE THREAD

**Issue by lubianat** [lubianat/annotate_them_all#10]
Nice, so you have an idea! These are optional guidelines to help you share them with the group. 

** What is your idea? **
Manually annotate some eLife abstracts with Wikidata IDs. 
Note down what can and cannot currently be annotated with Wikidata IDs. 

Use manual annotation to guide development of the gamified interface. 

** What can we do at the Sprint? **
We can annnotate, perhaps, one or 2 abstracts. 

**What skills does it require?**
Basic understanding of Wikidata (reading [this text](https://www.wikidata.org/wiki/Help:About_data) should be enough). 
Basic understanding of Europe PMC's Annotation API annotation format (reading [this page](https://europepmc.org/AnnotationsSubmission) should be enough).

**Comment by lubianat** [comment]
Perhaps a subtask would be to make a "manual annotator" that people could enter the information and the app (a shiny app perhaps?) would generate the Europe PMC-compatible JSON.

**Comment by lubianat** [comment]
The annotation is made in the W3C Web Annotation Data Model: 

https://www.w3.org/TR/annotation-model/

This might require quite a bit of coding on one side. But we can make "code-less" annotations in one side, matched by coe-related annotations in the other side.

**Comment by gtsueng** [comment]
**"Note down what can and cannot currently be annotated with Wikidata IDs."**

And please share those notes with the Gene Wiki/Wikidata community as well--especially if there are entities with existing ontologies that can be uploaded to Wikidata.

**Comment by lubianat** [comment]
Thanks, @gtsueng! 

We took notes in [this spreadsheet](https://docs.google.com/spreadsheets/d/1jmqW9GV04rxFwPiyidGOLN0NUzN-OWfzCkqB7RdwJbY/edit?usp=sharing)

I'm summarizing the work, and we should put a report out in a couple days, and try to make it reach anyone that might be interested. 

I'm closing the issue as the sprint has finished. There will be some follow up on the manual annotations on issue #28.
