### ISSUE TITLE
We need a name for the tool! 

### ISSUE THREAD

**Issue by lubianat** [lubianat/annotate_them_all#16]
Annotate Them All may not be the optimal name for our project/tool. Good names have to be a bit cryptic and/or sound nice, like "Pikachu" or "spaCy" or "BLAST" or "eLife Sprint" .

Is there any mythological/historical/cultural being/person that we can relate to ", "lots of texts",  knowledge and science or something like that? 

All (respectful) ideas are good ideas!

**Comment by arupgsh** [comment]
What about Annothena?
Annotation+Athena(Greek goddess of wisdom)

**Comment by lubianat** [comment]
It is already better than before!

Maybe something more cryptic? It can be really  far from annotation, in a far fetched abstraction. 

There a lot of cool light deities: https://en.wikipedia.org/wiki/List_of_light_deities

I also like the Hitchhiker's Guide to the Galaxy a lot, so I wouldn't mind a reference to that too :) 
For example, Magrathea is the planet where people built a huge computer to find the answer to "LIfe, the Universe and Everything", and became engineers of planets, build Earth and so on.  
It would not have an exact symbology, but the name "Magrathea" sounds quite awesome to me!
ref: https://hitchhikers.fandom.com/wiki/Magrathea

EDIT: I am fine with any name, really, we should gather a few ideas and them put them for a vote

**Comment by paranhosba** [comment]
I like messy brainstorms, so I'll drop some suggestions: 
-Miner
-ANN
-Sherlock (that's certainly taken already...)
-Spotter

**Comment by lubianat** [comment]
Dasapta (a sprint facilitator) mentioned that we could have a name that showed the connection with Wikidata :)

**Comment by ineshojas** [comment]
I like the idea of mentioning notes.

Sadly, WikiNotes already exists..

Maybe:
- DataNotes?
- Micro-notes?
- Bit-notes (as the minimum unit of concept)

**Comment by lubianat** [comment]
Well, we made it! Here comes Ann :)
