### ISSUE TITLE
Sketch an user interface 

### ISSUE THREAD

**Issue by lubianat** [lubianat/annotate_them_all#18]
How would an ideal user interface for this tool look like? 
Big buttons, small buttons? Mobile version and desktop version? 

We can be creative and draw a few ideas for the user interface!

**Comment by DayaneRAraujo** [comment]
![Page0](https://user-images.githubusercontent.com/52827039/92152609-e06cab80-ee1a-11ea-86f2-69979015b59e.png)
![Page0 1](https://user-images.githubusercontent.com/52827039/92152616-e3679c00-ee1a-11ea-8412-2f8ce067a2ff.png)
![Page1](https://user-images.githubusercontent.com/52827039/92152623-e5c9f600-ee1a-11ea-9171-b6e33a31b8ab.png)
![Page2](https://user-images.githubusercontent.com/52827039/92152632-e8c4e680-ee1a-11ea-99b6-65c0b743cd77.png)
![Page3](https://user-images.githubusercontent.com/52827039/92152640-ebbfd700-ee1a-11ea-9e59-139e0262c821.png)
![Page4](https://user-images.githubusercontent.com/52827039/92152656-efebf480-ee1a-11ea-9d3a-59b00b1d60e0.png)
![Pagina5](https://user-images.githubusercontent.com/52827039/92152710-05f9b500-ee1b-11ea-8b3d-6bfe5b6494a8.png)
![Page6](https://user-images.githubusercontent.com/52827039/92152728-101bb380-ee1b-11ea-89ef-90bf6027b7ed.png)
![Page7](https://user-images.githubusercontent.com/52827039/92152736-114ce080-ee1b-11ea-9316-66ebe17fc308.png)

**Comment by DayaneRAraujo** [comment]
![Page0](https://user-images.githubusercontent.com/52827039/92152802-33def980-ee1b-11ea-8344-645e13c65c23.png)

**Comment by DayaneRAraujo** [comment]
![Page0 1](https://user-images.githubusercontent.com/52827039/92152815-393c4400-ee1b-11ea-862d-63200af3ae72.png)

**Comment by DayaneRAraujo** [comment]
![Page1](https://user-images.githubusercontent.com/52827039/92152828-3e998e80-ee1b-11ea-9e74-6ec43f85421f.png)

**Comment by DayaneRAraujo** [comment]
![Page2](https://user-images.githubusercontent.com/52827039/92152846-448f6f80-ee1b-11ea-913a-7a5682e467fe.png)

**Comment by DayaneRAraujo** [comment]
![Page3](https://user-images.githubusercontent.com/52827039/92152881-553fe580-ee1b-11ea-92c6-f518a003549e.png)

**Comment by DayaneRAraujo** [comment]
![Page4](https://user-images.githubusercontent.com/52827039/92152895-596c0300-ee1b-11ea-92e8-9b5a8d948bac.png)

**Comment by DayaneRAraujo** [comment]
![Pagina5](https://user-images.githubusercontent.com/52827039/92152905-5e30b700-ee1b-11ea-9549-6f105998a954.png)

**Comment by DayaneRAraujo** [comment]
![Page6](https://user-images.githubusercontent.com/52827039/92152920-62f56b00-ee1b-11ea-9e2c-a0dde722c6fd.png)

**Comment by DayaneRAraujo** [comment]
![Page7](https://user-images.githubusercontent.com/52827039/92152931-6688f200-ee1b-11ea-996d-56e88e274a36.png)

**Comment by lubianat** [comment]
Awesome, @DayaneRAraujo ! I'll close the issue (it is archived, and available later).
