### ISSUE TITLE
Compile existing tools that rely on identifying concepts 

### ISSUE THREAD

**Issue by lubianat** [lubianat/annotate_them_all#20]
**What is your idea?**
There are many tools already that deal with concept identification. A couple of them are already listed at https://github.com/lubianat/annotate_them_all/wiki/Related-works . But surely there are many out there! 

To compile a list of exsiting tools would be great, so we can see how the project fits in the larger community.

**Comment by webersab** [comment]
We compiled a list with tools and small feasability analysis here: https://docs.google.com/document/d/1wBKcsdk6g6RwLnq3IpRuOVdONGsIrcm537NP4frJAYQ/edit

**Comment by lubianat** [comment]
done
