### ISSUE TITLE
Increase accuracy of Wikidata API search

### ISSUE THREAD

**Issue by arupgsh** [lubianat/annotate_them_all#23]
Is there any way to classify the entity based on the category and context.

```
Eg.
Apple Inc > Company
Apple > Fruit
```

**Comment by webersab** [comment]
I read the paper and it seems like sci spacy does not use contextualized word embeddings (the model they usde is described here: https://arxiv.org/pdf/1603.01360.pdf). There is some code for detecing and normalizing biomedical entities using contextualized word embeddings here:  https://bern.korea.ac.kr/ We could try and see if this is better at detecting the entities than sci spacy. We would still have to link the entites to Wikidata, but maybe we could use that in addition to sci spacy.
