### ISSUE TITLE
Organize and refactor current files

### ISSUE THREAD

**Issue by lubianat** [lubianat/annotate_them_all#29]
During the sprint, we might have some less-than-optimal file names and code organization. We need to improve this. 

Oh, any pull requests that improves that are welcome! 

Quickly take a look at the [contributing guidelines](https://github.com/lubianat/ann/blob/master/CONTRIBUTING.md), and good to go.

**Comment by jvfe** [comment]
If no one else is working on this, I could try helping a bit.

**Comment by lubianat** [comment]
@jvfe go for it!
