### ISSUE TITLE
Create a logo for the project

### ISSUE THREAD

**Issue by lubianat** [lubianat/annotate_them_all#6]
Creating a logo makes the project looks professional and helps to get more contributors!

**Comment by paranhosba** [comment]
![Captura de Tela 2020-09-02 às 11 33 28](https://user-images.githubusercontent.com/70616887/91997194-356fcb00-ed10-11ea-8bfe-56cd6884e075.png)

Here are some ideas! I used a simple color scheme, but we can adapt to the red-blue-green mentioned by Tiago earlier. I've put numbers on them so everyone can share their thoughts

**Comment by DayaneRAraujo** [comment]
They are really cool! I really like number 3 and 5 most.

**Comment by lubianat** [comment]
Nice! I liked the ones where the annotations pop out, because it brings up the idea that the text is going somewhere else. 

In the end, an annotation is a hyperlink

**Comment by ineshojas** [comment]
I really like numbers 3 and 5!! 

I had a previous quite rough logo draft but that was specific for one of the names (something like micro-notes), so I guess we could adapt it later.

Anyways, I will just leave it there as well for you to see

![logo u-note](https://user-images.githubusercontent.com/70634397/92008550-9bc41000-ed47-11ea-8649-01ab664ee2d2.jpg)

**Comment by lubianat** [comment]
Awesome work everyone, logo is on the slack channel and as the GitHub social media preview already!
